### ISSUE TITLE
Score Submission Validation

### ISSUE THREAD

**Issue by GHAngeloid** [Reyder95/sdvx-tracker-frontend#107]
This is a mix of bug and feature request. As of right now, there is only a case check in `song-view.js` for scores between `0` and `10,000,000`. No validation for `clear type`.

For example, I can submit a `10,000,000` score for other clear types when it should be `Perfect Ultimate Chain` only.

Another example, submitting a score of `1` to `Ultimate Chain` and `Perfect Ultimate Chain` clear types.

Suggestion: Add clear type case checks in `addScoreToAPI()` function in `song-view.js` before making call to `addScore()` function in `api-calls.js`.

**Comment by Reyder95** [comment]
Yeah I was planning on doing a few things. For one, when typing 10,000,000 it would instantly select PUC. However what do you think would be a plausible Ultimate Chain? I think at the moment something like PUC is the only thing you can safely check.

**Comment by GHAngeloid** [comment]
You could refactor how you submit a score by adding a `chain` attribute. You know that it requires max chain to be counted as UC or PUC. Having only score won't be feasible.

**Comment by Reyder95** [comment]
Indeed but as it stands adding more would be sort of annoying to do. Since things are manual, simplicity is what I went with. It's entirely an honor system so things like that aren't so bad to deal with. I'll be just checking PUC for now. If something changes in the future I'll handle UC as well.
